### ISSUE TITLE
Cursor update in shrink necessary?

### ISSUE THREAD

**Issue by hakase56557** [project-starch/capstone-spec#38]
In `shrink`:
If `x[rd].cursor < x[rs1]`, set `x[rd].cursor` to `x[rs1]`.
If `x[rd].cursor > x[rs2]`, set `x[rd].cursor` to `x[rs2]`.

Can we do with changing the cursor to one of `x[rs1]` or `x[rs2]`? Or maybe not update the cursor at all.
Removing the above check may also help with simplifying the hardware logic for the instruction

**Comment by Mingkai-Li** [comment]
Sorry for the slow response.

The cursor update for the SHRINK instruction is to make the *cursor* of an *uninitialized capability* remain valid, i.e., within the bounds, after this instruction.

If the cursor is not updated atomically during instruction, it would be difficult to set the cursor within the bounds afterward. Hence, it would be difficult for some instructions, e.g., store instructions, INIT, etc. to take this capability as an operand.

Add a special check to the `type` field before the cursor update might be a hardware overhead as well, if we consider such cursor update might be rare in real applications.

Similar concerns exist regarding *"changing the cursor to one of x[rs1] or x[rs2]"*, when it comes to the uninitialized capability.
